added config file in the backup dir.

diff --git a/yarsa b/yarsa
--- a/yarsa
+++ b/yarsa
@@ -17,6 +17,38 @@
 #
 #  0. You just DO WHAT THE FUCK YOU WANT TO.
 
+set -e
+
+# Default configuration
+# todo: link to the git describe --tags
+VERSION="1.0"
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+
+# Complete path to backup server in the form of
+# server::modulo
+BACKUP_FROM=$1
+
+# Dir where to store the incremental backups
+# ex. /backup/myserver.com/
+BACKUP_TO=$2
+
+# Number of backups to keep
+KEEP_DIR_NO=$3
+
+# Local Config file
+CONFFILE=$BACKUP_TO/yarsa.cfg
+
+# The exclude file, lists of all file not to be backed UP
+EXCLUDE_FILE=$BACKUP_TO/yarsa_exclude.cfg
+
+# The rsync command to use.
+RSYNC_SWITCH="-av --delete --delete-excluded --ignore-errors --whole-file --numeric-ids --exclude-from=$EXCLUDE_FILE"
+
+# Read the local conffile
+if [ -r "$CONFFILE" ]; then
+    . $CONFFILE
+fi
+
 # Perform some safety checks before starting the backup.
 function do_checks() {
 # Number of backups > 0
@@ -26,6 +58,7 @@ if [ $KEEP_DIR_NO -gt 0 ]; then
     echo "OK]"
 else
     echo "FAILED]"
+    echo "... missing number of backups to keep."
     exit 1
 fi
 
@@ -36,17 +69,33 @@ if [ -d "$BACKUP_TO" ] && [ -d "$LINK_DIR" ] && [ ! -e $NEW_BCK_DIR ]; then
     echo "OK]"
 else
     echo "FAILED]"
+    echo "... missing $BACKUP_TO or $LINK_DIR, $NEW_BCK_DIR"
+    echo "... OR $LINK_DIR is the same of $NEW_BCK_DIR, wait 1 minute."
     exit 1
 fi
 
-# Check for the exclude file in backups directory
-echo -n "Check exclude file: $EXCLUDE_FILE ... ["
+# Check for the config file in backups directory
+echo -n "Check config file: $CONFFILE ... ["
 
-if [ -f "$EXCLUDE_FILE" ]; then
+if [ -f "$CONFFILE" ]; then
     echo "OK]"
 else
     echo "FAILED]"
+    echo "... missing $CONFFILE"
     exit 1
+fi
+
+# Check for the exclude file in backups directory if defined.
+if [ -v EXCLUDE_FILE ]; then
+    echo -n "Check exclude file: $EXCLUDE_FILE ... ["
+
+    if [ -f "$EXCLUDE_FILE" ]; then
+        echo "OK]"
+    else
+        echo "FAILED]"
+        echo "... missing $EXCLUDE_FILE"
+        exit 1
+    fi
 fi
 }
 
@@ -95,27 +144,6 @@ fi
 }
 
 ## Main
-# todo: link to the git describe --tags
-VERSION="1.0"
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-
-# Complete path to backup server in the form of
-# server::modulo
-BACKUP_FROM=$1
-
-# Dir where to store the incremental backups
-# ex. /backup/myserver.com/
-BACKUP_TO=$2
-
-# Number of backups to keep
-KEEP_DIR_NO=$3
-
-# The exclude file, lists of all file not to be backed UP
-EXCLUDE_FILE=$BACKUP_TO/yarsa_exclude.cfg
-
-# The rsync command to use.
-RSYNC_SWITCH="-av --delete --delete-excluded --ignore-errors --whole-file --numeric-ids --exclude-from=$EXCLUDE_FILE"
-
 # Actual number of backups directory
 BCK_NO=$(find $BACKUP_TO -maxdepth 1 -type d -name "rsb_*" | wc -l)
 BCK_LIST=$(find $BACKUP_TO -maxdepth 1 -type d -name "rsb_*" | sort)
